/* eslint-disable @typescript-eslint/no-unused-vars */
import { useEffect, useState } from "react"
import axios from "axios"
import { NFTStorage } from "nft.storage"
import pLimit from "p-limit"

import {
  b64toBlob,
  bulkMint,
  deployContract,
  setFolderStorage,
  uploadFolder,
  uploadNft,
} from "@/utils/mintUtils"

import SimpleHeader from "../Common/SimpleHeader"

import { useRequestStatus } from "./Hooks/useRequestStatus"
import ConfirmationStep from "./ConfirmationStep"
import DesignStep from "./DesignStep"
import FormStep from "./FormStep"
import { NftBuilderStyles } from "./NftBuilderStyles"
import StepsHeader from "./StepsHeader"

const NFT_STORAGE_TOKEN = process.env.NEXT_PUBLIC_NFT_STORAGE_KEY ?? ""
const storage = new NFTStorage({ token: NFT_STORAGE_TOKEN })

declare global {
  interface Window {
    canvas: any
    uploadedNfts: any
  }
}

const NftBuilder = ({ artists }: any) => {
  const [nftTitle, setNftTitle] = useState("")
  const [nftDescription, setNftDescription] = useState("")
  const [images, setImages] = useState([])
  const [memberImage, setMemberImage] = useState("")
  const [activeStep, setActiveStep] = useState(1)
  const [uploading, setUploading] = useState(false)
  const [uploadedCount, setUploadedCount] = useState(0)
  const [selectedArtist, setSelectedArtist] = useState(artists[0])
  const [errorMessage, setErrorMessage] = useState("")
  const [contractAddress, setContractAddress] = useState("")
  const [contractDeployed, setContractDeployed] = useState(false)
  const [formValues, setFormValues] = useState({
    name: "AUTOGENERATED",
    wallet: "",
    size: "10",
    passType: "Lottery",
    saleType: "Fixed",
    price: "0.1",
    duration: "24",
    winners: "5",
    date: new Date(),
    is_charity: false,
    charity_name: "",
    charity_royalty: "",
  })

  const {
    requestStatus: contractDeployStatus,
    requestData,
    setRequestId,
  } = useRequestStatus()

  useEffect(() => {
    if (contractAddress) {
      console.log("Contract: " + contractAddress)
      createCollection()
    }
  }, [contractAddress])

  useEffect(() => {
    if (requestData?.contractAddress) {
      setContractAddress(requestData.contractAddress)
    }
  }, [requestData])

  useEffect(() => {
    // @ts-ignore
    window.canvas = false
    window.uploadedNfts = 0
    sessionStorage.removeItem("collectionData")
    sessionStorage.removeItem("canvasJson")
    setUploading(false)
  }, [])

  const nextStep = () => {
    setActiveStep(activeStep + 1)
  }

  const previousStep = () => {
    setActiveStep(activeStep - 1)
  }

  const onFormSave = (values: any) => {
    nextStep()
    setFormValues(values)
  }

  const submit = async (imges: any) => {
    setImages(imges)
    setUploading(true)
    setUploadedCount(0)
    // This will request a contract deployment.
    // Once ready, the contractAddress useEffect will create the collection

    try {
      const reqId = await deployContract(formValues)
      setRequestId(reqId)
    } catch (error) {
      setErrorMessage(JSON.stringify(error))
    }
  }

  // This is called when contractAddress is set
  const createCollection = async () => {
    const premint = formValues.saleType == "Auction"
    if (uploading) {
      const batchSize = 10
      // Upload first image to use as preview
      const blob = b64toBlob(images[0])
      const nftKey = await storage.storeBlob(blob)
      // Creates the pass, to then associate NFTs to it
      const passResponse = await axios.post("/api/passes/create", {
        ...formValues,
        contract_address: contractAddress,
        preview_image_url: "https://plusonemusic.io/ipfs/" + nftKey,
      })

      // Array used to store the metadata files that will be later uploaded
      const metadatas: any[] = []
      const limit = pLimit(batchSize)
      for (let i = 0; i < images.length; i += batchSize) {
        const batch = images.slice(i, i + batchSize)
        const promises = batch.map((image: any, j: number) => {
          if (image) {
            setUploadedCount(i + j)
            return limit(() =>
              uploadNft(
                image,
                passResponse.data.data.id,
                i + j,
                metadatas,
                formValues,
                nftTitle
              )
            )
          }
        })
        await Promise.all(promises)
        // NFT Storage limits to 10 requests every 5 seconds, add wait
        await new Promise((resolve) => setTimeout(resolve, 5 * 1000))
      }
      if (premint) {
        try {
          const folderCid = await uploadFolder(contractAddress, metadatas)
          await setFolderStorage(contractAddress, folderCid)
          await bulkMint(contractAddress, formValues.size)
        } catch (error) {
          setErrorMessage(JSON.stringify(error))
        }
      }
      setUploading(false)
      setContractDeployed(true)
    }
  }

  return (
    <NftBuilderStyles>
      <SimpleHeader title="NFT Collection Generator" />
      <StepsHeader activeStep={activeStep} />
      <section className="steps">
        <div className="content">
          {activeStep == 1 && (
            <FormStep
              formValues={formValues}
              nextAction={onFormSave}
              artists={artists}
              setNftTitle={setNftTitle}
              nftTitle={nftTitle}
              nftDescription={nftDescription}
              setNftDescription={setNftDescription}
              setMemberImage={setMemberImage}
              setSelectedArtist={setSelectedArtist}
              selectedArtist={selectedArtist}
            />
          )}
          {activeStep == 2 && (
            <DesignStep
              nftName={formValues.name}
              nextAction={nextStep}
              previousAction={previousStep}
              artist={selectedArtist}
              memberImage={memberImage}
            />
          )}
          {activeStep == 3 && (
            <>
              <ConfirmationStep
                formValues={formValues}
                nextAction={submit}
                previousAction={previousStep}
                uploading={uploading}
                uploaded={uploadedCount}
                contractDeployed={contractDeployed}
                contractAddress={contractAddress}
                errorMessage={errorMessage}
              />
            </>
          )}
        </div>
      </section>
    </NftBuilderStyles>
  )
}

export default NftBuilder
