import { Field, Form, Formik, useFormik } from "formik"
import DatePicker from "react-datepicker"
import * as Yup from "yup"

import { CommonPill } from "@/components/Common/CommonStyles"

import { FormStepStyles } from "./FormStepStyles"

import "react-datepicker/dist/react-datepicker.css"

const FormStep = ({ formValues, nextAction, artists }: any) => {
  const validationSchema = Yup.object().shape({
    name: Yup.string().required("Please enter your project name"),
    dropDate: Yup.string().required("Please enter the mint date"),
    wallet: Yup.string().required("Please enter your wallet"),
    size: Yup.number().required("Please enter your collection size."),
    passType: Yup.string().required("Please enter your pass type"),
    saleType: Yup.string().required("Please enter your sale type"),
    price: Yup.number().required("Please enter your price"),
  })

  interface FormValues {
    name: string
    dropDate: Date
    wallet: string
    size: number
    passType: string
    saleType: string
    artist: number
    show: string
    duration: number
    price: number
    tourFrom: Date
    tourTo: Date
    lotteryDate: Date
  }

  const submit = async (values: FormValues) => {
    console.log(values)
    nextAction(values)
  }

  const generateName = (
    artistIndex: any,
    passType: any,
    setFieldValue: any
  ) => {
    const sel = artists[artistIndex]
    setFieldValue("name", `${sel.attributes.name} ${passType} Pass`)
  }

  return (
    <FormStepStyles>
      <h2>Project Metadata</h2>
      <Formik
        initialValues={formValues}
        onSubmit={submit}
        validationSchema={validationSchema}
      >
        {({ values, setFieldValue, errors, touched }) => (
          <Form className="generator-form trap">
            <label>
              <span>Collection name</span>
              <input
                className="name-field"
                type="text"
                name="name"
                value={values.name}
                placeholder="AUTOGENERATED"
                readOnly
              />
            </label>
            <label>
              <span>Artist</span>
              {errors.artist && touched.artist ? (
                <div className="alert">{errors.artist}</div>
              ) : null}
              <Field
                name="artist"
                as="select"
                onChange={(e: any) => {
                  setFieldValue("artist", e.target.value),
                    generateName(e.target.value, values.passType, setFieldValue)
                }}
              >
                <option value="">-</option>
                {artists.length &&
                  artists.map((item: any, index: number) => (
                    <option key={"artist-item" + index} value={index}>
                      {item.attributes.name}
                    </option>
                  ))}
              </Field>
            </label>
            <label>
              <span>Royalty Wallet Address</span>
              {errors.wallet && touched.wallet ? (
                <div className="alert">{errors.wallet}</div>
              ) : null}
              <Field type="text" name="wallet" />
            </label>
            <label>
              <span>Collection size</span>
              {errors.size && touched.size ? (
                <div className="alert">{errors.size}</div>
              ) : null}
              <Field type="number" name="size" />
            </label>
            <label>
              <span>Pass Type</span>
              {errors.passType && touched.passType ? (
                <div className="alert">{errors.passType}</div>
              ) : null}
              <Field
                name="passType"
                as="select"
                onChange={(e: any) => {
                  setFieldValue("passType", e.target.value),
                    generateName(values.artist, e.target.value, setFieldValue)
                }}
              >
                <option value="">-</option>
                <option value="lifetime">Lifetime</option>
                <option value="lottery">Lottery</option>
                <option value="tour">Tour</option>
                <option value="single">Single Event</option>
              </Field>
            </label>
            <label>
              <span>Sale Type</span>
              {errors.saleType && touched.saleType ? (
                <div className="alert">{errors.saleType}</div>
              ) : null}
              <Field name="saleType" as="select">
                <option value="">-</option>
                <option value="auction">Auction</option>
                <option value="fixed">Fixed Price</option>
              </Field>
            </label>
            {values.passType == "tour" && (
              <>
                <label>
                  <span>Tour start date</span>
                  {errors.tourFrom && touched.tourFrom ? (
                    <div className="alert">{errors.tourFrom}</div>
                  ) : null}
                  <DatePicker
                    showTimeSelect
                    dateFormat="Pp"
                    name="tourFrom"
                    selected={values.tourFrom}
                    onChange={(tourFrom) => setFieldValue("tourFrom", tourFrom)}
                  />
                </label>

                <label>
                  <span>Tour end date</span>
                  {errors.tourTo && touched.tourTo ? (
                    <div className="alert">{errors.tourTo}</div>
                  ) : null}
                  <DatePicker
                    showTimeSelect
                    dateFormat="Pp"
                    name="tourTo"
                    selected={values.tourTo}
                    onChange={(tourTo) => setFieldValue("tourTo", tourTo)}
                  />
                </label>
              </>
            )}
            {values.passType == "single" && (
              <label>
                <span>Show</span>
                <Field name="show" as="select">
                  <option value="">-</option>
                </Field>
              </label>
            )}
            <label>
              {values.saleType == "auction" ? (
                <span>Initial auction price (ETH)</span>
              ) : (
                <span>Fixed price (ETH)</span>
              )}
              {errors.price && touched.price ? (
                <div className="alert">{errors.price}</div>
              ) : null}
              <Field type="number" name="price" />
            </label>
            <label>
              <span>Drop date</span>
              {errors.dropDate && touched.dropDate ? (
                <div className="alert">{errors.dropDate}</div>
              ) : null}
              <DatePicker
                showTimeSelect
                dateFormat="Pp"
                name="dropDate"
                selected={values.dropDate}
                onChange={(dropDate) => setFieldValue("dropDate", dropDate)}
              />
            </label>
            {values.saleType == "auction" && (
              <label>
                <span>Duration (Hours)</span>
                <Field name="duration" type="text" />
              </label>
            )}

            <div className="buttons">
              <button type="submit">
                <CommonPill className="clickable">Next</CommonPill>
              </button>
            </div>
          </Form>
        )}
      </Formik>
    </FormStepStyles>
  )
}

export default FormStep
